import "dotenv/config"
import { PrismaClient, Region, HospitalType, InsuranceType, Prisma } from "@prisma/client"

const prisma = new PrismaClient({ accelerateUrl: process.env.DATABASE_URL })

// ─── Helpers ──────────────────────────────────────────────────────────────────

type JsonObj = { [k: string]: Prisma.InputJsonValue }

function bdSchedule(
  days: string[],
  morning?: { start: string; end: string },
  evening?: { start: string; end: string },
  max = 20,
): Prisma.InputJsonObject {
  const schedule: JsonObj = {}
  days.forEach((d) => {
    if (morning && evening) {
      schedule[d] = { morning: morning as Prisma.InputJsonValue, evening: evening as Prisma.InputJsonValue, maxPatients: max }
    } else if (morning) {
      schedule[d] = { start: morning.start, end: morning.end, maxPatients: max }
    }
  })
  return schedule as Prisma.InputJsonObject
}

function usSchedule(days: string[], start: string, end: string, max = 24): Prisma.InputJsonObject {
  const schedule: JsonObj = {}
  days.forEach((d) => {
    schedule[d] = { start, end, maxPatients: max }
  })
  return schedule as Prisma.InputJsonObject
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("🌱  Seeding PikiMed database…")

  // ── Clean slate ──────────────────────────────────────────────────────────────
  await prisma.review.deleteMany()
  await prisma.hospitalInsurance.deleteMany()
  await prisma.affordableClinic.deleteMany()
  await prisma.costEstimate.deleteMany()
  await prisma.doctor.deleteMany()
  await prisma.hospital.deleteMany()
  await prisma.insurancePlan.deleteMany()
  await prisma.user.deleteMany()

  // ── Users ────────────────────────────────────────────────────────────────────
  const [u1, u2, u3, u4, u5, u6, u7, u8, u9, u10] = await Promise.all([
    // Bangladesh
    prisma.user.create({ data: { name: "Rahim Uddin",    email: "rahim@pikimed.test",   region: Region.BD } }),
    prisma.user.create({ data: { name: "Nasrin Akter",   email: "nasrin@pikimed.test",  region: Region.BD } }),
    prisma.user.create({ data: { name: "Kamal Hossain",  email: "kamal@pikimed.test",   region: Region.BD } }),
    prisma.user.create({ data: { name: "Fatema Begum",   email: "fatema@pikimed.test",  region: Region.BD } }),
    prisma.user.create({ data: { name: "Arif Rahman",    email: "arif@pikimed.test",    region: Region.BD } }),
    // United States
    prisma.user.create({ data: { name: "John Smith",     email: "john@pikimed.test",    region: Region.US } }),
    prisma.user.create({ data: { name: "Emily Davis",    email: "emily@pikimed.test",   region: Region.US } }),
    prisma.user.create({ data: { name: "Michael Brown",  email: "michael@pikimed.test", region: Region.US } }),
    prisma.user.create({ data: { name: "Jessica Wilson", email: "jessica@pikimed.test", region: Region.US } }),
    prisma.user.create({ data: { name: "Robert Taylor",  email: "robert@pikimed.test",  region: Region.US } }),
  ])
  console.log("  ✓ Users")

  // ── Bangladesh Doctors ───────────────────────────────────────────────────────
  const [bd1, bd2, bd3, bd4, bd5, bd6, bd7, bd8, bd9, bd10, bd11, bd12] =
    await Promise.all([
      // Dhaka
      prisma.doctor.create({
        data: {
          name: "Dr. Md. Abdur Rahman",
          slug: "dr-abdur-rahman",
          specialty: "Cardiology",
          bio: "Professor of Cardiology at Dhaka Medical College with 25+ years of experience in interventional cardiology and heart failure management.",
          region: Region.BD,
          city: "Dhaka",
          district: "Dhaka",
          lat: 23.726_1,
          lng: 90.388_5,
          phone: "+8801711-234567",
          email: "abdur.rahman@dmch.gov.bd",
          bmdc: "A-45231",
          consultFeeMin: 800,
          consultFeeMax: 1500,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "sunday", "monday"],
            { start: "09:00", end: "13:00" },
            { start: "17:00", end: "20:00" },
            25,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 45,
          avgRating: 4.7,
          reviewCount: 8,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Shahana Khatun",
          slug: "dr-shahana-khatun",
          specialty: "Gynecology",
          bio: "Senior Consultant Gynecologist & Obstetrician at Square Hospital. Specialist in high-risk pregnancies and laparoscopic surgery.",
          region: Region.BD,
          city: "Dhaka",
          district: "Dhaka",
          lat: 23.753_1,
          lng: 90.370_1,
          phone: "+8801812-345678",
          email: "shahana@squarehospital.com",
          bmdc: "A-38920",
          consultFeeMin: 1000,
          consultFeeMax: 2000,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["sunday", "tuesday", "thursday"],
            { start: "10:00", end: "14:00" },
            { start: "17:00", end: "21:00" },
            20,
          ),
          isAvailableToday: false,
          avgWaitMinutes: 30,
          avgRating: 4.8,
          reviewCount: 6,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Farhad Hossain",
          slug: "dr-farhad-hossain",
          specialty: "Neurology",
          bio: "Associate Professor of Neurology, BIRDEM General Hospital. Expert in epilepsy, stroke management, and neurodegenerative diseases.",
          region: Region.BD,
          city: "Dhaka",
          district: "Dhaka",
          lat: 23.744_2,
          lng: 90.394_4,
          phone: "+8801912-456789",
          email: "farhad.neuro@birdem.com",
          bmdc: "A-51670",
          consultFeeMin: 1200,
          consultFeeMax: 2500,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "monday", "wednesday"],
            { start: "09:00", end: "12:00" },
            { start: "18:00", end: "21:00" },
            15,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 60,
          avgRating: 4.6,
          reviewCount: 5,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Nasrin Begum",
          slug: "dr-nasrin-begum",
          specialty: "Diabetes & Endocrinology",
          bio: "Senior Diabetologist at BIRDEM. Over 20 years managing type-1, type-2 diabetes, thyroid disorders, and obesity clinics.",
          region: Region.BD,
          city: "Dhaka",
          district: "Dhaka",
          lat: 23.744_5,
          lng: 90.394_0,
          phone: "+8801611-567890",
          email: "nasrin.dm@birdem.com",
          bmdc: "A-29815",
          consultFeeMin: 800,
          consultFeeMax: 1500,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["sunday", "tuesday", "thursday", "saturday"],
            { start: "08:00", end: "12:00" },
            undefined,
            30,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 50,
          avgRating: 4.9,
          reviewCount: 7,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Khondaker Abul Islam",
          slug: "dr-khondaker-islam",
          specialty: "General Medicine",
          bio: "General physician at Ibn Sina Hospital, Dhanmondi. Compassionate care for all age groups with focus on preventive medicine.",
          region: Region.BD,
          city: "Dhaka",
          district: "Dhaka",
          lat: 23.780_9,
          lng: 90.403_7,
          phone: "+8801711-678901",
          bmdc: "A-63421",
          consultFeeMin: 500,
          consultFeeMax: 800,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "sunday", "monday", "tuesday", "wednesday"],
            { start: "09:00", end: "13:00" },
            { start: "17:00", end: "20:00" },
            35,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 25,
          avgRating: 4.5,
          reviewCount: 4,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Tahmina Akter",
          slug: "dr-tahmina-akter",
          specialty: "Cardiology",
          bio: "Consultant Cardiologist at Evercare Hospital. Trained at NICVD, specializing in echocardiography and cardiac catheterization.",
          region: Region.BD,
          city: "Dhaka",
          district: "Dhaka",
          lat: 23.822_3,
          lng: 90.415_3,
          phone: "+8801812-789012",
          email: "tahmina.cardio@evercarebd.com",
          bmdc: "A-72345",
          consultFeeMin: 2000,
          consultFeeMax: 4000,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["sunday", "monday", "wednesday", "thursday"],
            { start: "10:00", end: "13:00" },
            { start: "18:00", end: "21:00" },
            18,
          ),
          isAvailableToday: false,
          avgWaitMinutes: 35,
          avgRating: 4.8,
          reviewCount: 6,
        },
      }),
      // Chittagong
      prisma.doctor.create({
        data: {
          name: "Dr. Rafiqul Alam",
          slug: "dr-rafiqul-alam",
          specialty: "General Medicine",
          bio: "General physician with 18 years of practice in Chittagong. Known for thorough clinical examination and patient-friendly approach.",
          region: Region.BD,
          city: "Chittagong",
          district: "Chittagong",
          lat: 22.356_9,
          lng: 91.834_5,
          phone: "+8801711-890123",
          bmdc: "A-44892",
          consultFeeMin: 500,
          consultFeeMax: 800,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "sunday", "monday", "tuesday", "thursday"],
            { start: "09:00", end: "14:00" },
            { start: "17:00", end: "20:00" },
            30,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 20,
          avgRating: 4.4,
          reviewCount: 3,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Sadia Sultana",
          slug: "dr-sadia-sultana",
          specialty: "Cardiology",
          bio: "Cardiologist at Chevron Hospital, Chittagong. Expertise in hypertension management, cardiac imaging, and preventive cardiology.",
          region: Region.BD,
          city: "Chittagong",
          district: "Chittagong",
          lat: 22.349_8,
          lng: 91.820_4,
          phone: "+8801912-901234",
          email: "sadia.cardio@chevronbd.com",
          bmdc: "A-55671",
          consultFeeMin: 1000,
          consultFeeMax: 2000,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "monday", "wednesday"],
            { start: "10:00", end: "14:00" },
            { start: "17:00", end: "20:00" },
            20,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 40,
          avgRating: 4.7,
          reviewCount: 4,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Imran Khan",
          slug: "dr-imran-khan-ctg",
          specialty: "Diabetes & Endocrinology",
          bio: "Diabetologist practicing in Chittagong for 15 years. Active in diabetes education and community health programs.",
          region: Region.BD,
          city: "Chittagong",
          district: "Chittagong",
          lat: 22.360_2,
          lng: 91.830_1,
          phone: "+8801611-012345",
          bmdc: "A-61238",
          consultFeeMin: 800,
          consultFeeMax: 1500,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["sunday", "tuesday", "thursday"],
            { start: "09:00", end: "13:00" },
            { start: "17:00", end: "20:00" },
            22,
          ),
          isAvailableToday: false,
          avgWaitMinutes: 35,
          avgRating: 4.5,
          reviewCount: 3,
        },
      }),
      // Sylhet
      prisma.doctor.create({
        data: {
          name: "Dr. Mahmuda Khanam",
          slug: "dr-mahmuda-khanam",
          specialty: "Gynecology",
          bio: "Gynecologist and Obstetrician based in Sylhet. Experienced in normal and complicated deliveries, infertility treatment.",
          region: Region.BD,
          city: "Sylhet",
          district: "Sylhet",
          lat: 24.892_8,
          lng: 91.872_3,
          phone: "+8801812-123456",
          bmdc: "A-33547",
          consultFeeMin: 800,
          consultFeeMax: 1500,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "sunday", "tuesday", "wednesday"],
            { start: "09:00", end: "13:00" },
            { start: "17:00", end: "20:00" },
            20,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 30,
          avgRating: 4.6,
          reviewCount: 3,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Ahsan Habib",
          slug: "dr-ahsan-habib",
          specialty: "Neurology",
          bio: "Neurologist at Sylhet MAG Osmani Medical College. Managing stroke, migraine, and movement disorder patients in the greater Sylhet region.",
          region: Region.BD,
          city: "Sylhet",
          district: "Sylhet",
          lat: 24.897_4,
          lng: 91.875_6,
          phone: "+8801712-234567",
          bmdc: "A-48923",
          consultFeeMin: 1000,
          consultFeeMax: 2000,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "monday", "thursday"],
            { start: "09:00", end: "13:00" },
            { start: "17:00", end: "20:00" },
            18,
          ),
          isAvailableToday: false,
          avgWaitMinutes: 50,
          avgRating: 4.5,
          reviewCount: 2,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Rezaul Karim",
          slug: "dr-rezaul-karim",
          specialty: "General Medicine",
          bio: "Beloved family physician serving Sylhet for over 20 years. Affordable and accessible healthcare for all income groups.",
          region: Region.BD,
          city: "Sylhet",
          district: "Sylhet",
          lat: 24.883_5,
          lng: 91.864_2,
          phone: "+8801711-345678",
          bmdc: "A-27634",
          consultFeeMin: 400,
          consultFeeMax: 700,
          currency: "BDT",
          chamberSchedule: bdSchedule(
            ["saturday", "sunday", "monday", "tuesday", "wednesday", "thursday"],
            { start: "08:00", end: "14:00" },
            { start: "17:00", end: "20:00" },
            40,
          ),
          isAvailableToday: true,
          avgWaitMinutes: 20,
          avgRating: 4.7,
          reviewCount: 4,
        },
      }),
    ])
  console.log("  ✓ Bangladesh doctors")

  // ── Bangladesh Hospitals ──────────────────────────────────────────────────────
  const [bh1, bh2, bh3, bh4, bh5, bh6] = await Promise.all([
    prisma.hospital.create({
      data: {
        name: "Dhaka Medical College Hospital",
        slug: "dhaka-medical-college-hospital",
        type: HospitalType.GOVERNMENT,
        region: Region.BD,
        address: "Bakshibazar, Dhaka-1000",
        city: "Dhaka",
        district: "Dhaka",
        lat: 23.726_1,
        lng: 90.388_5,
        phone: "+880-2-55165088",
        emergencyPhone: "+880-2-55165000",
        isOpen24h: true,
        specialties: ["Cardiology", "Neurology", "Orthopedics", "Surgery", "Pediatrics", "Gynecology"],
        avgRating: 3.9,
        reviewCount: 9,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Square Hospital",
        slug: "square-hospital-dhaka",
        type: HospitalType.PRIVATE,
        region: Region.BD,
        address: "18/F Bir Uttam Qazi Nuruzzaman Sarak, West Panthapath, Dhaka-1205",
        city: "Dhaka",
        district: "Dhaka",
        lat: 23.753_1,
        lng: 90.370_1,
        phone: "+880-2-8159457",
        emergencyPhone: "+880-2-8159457",
        isOpen24h: true,
        openTime: "00:00",
        closeTime: "23:59",
        specialties: ["Cardiology", "Oncology", "Neurosurgery", "Gynecology", "Orthopedics", "Urology"],
        avgRating: 4.5,
        reviewCount: 8,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "BIRDEM General Hospital",
        slug: "birdem-general-hospital",
        type: HospitalType.PRIVATE,
        region: Region.BD,
        address: "122 Kazi Nazrul Islam Avenue, Shahbag, Dhaka-1000",
        city: "Dhaka",
        district: "Dhaka",
        lat: 23.744_2,
        lng: 90.394_4,
        phone: "+880-2-9661551",
        emergencyPhone: "+880-2-9661551",
        isOpen24h: true,
        specialties: ["Diabetes & Endocrinology", "Nephrology", "Cardiology", "Ophthalmology", "Nutrition"],
        avgRating: 4.6,
        reviewCount: 7,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Evercare Hospital Dhaka",
        slug: "evercare-hospital-dhaka",
        type: HospitalType.PRIVATE,
        region: Region.BD,
        address: "Plot 81, Block E, Bashundhara R/A, Dhaka-1229",
        city: "Dhaka",
        district: "Dhaka",
        lat: 23.822_3,
        lng: 90.415_3,
        phone: "+880-2-222279999",
        emergencyPhone: "+880-2-222279911",
        isOpen24h: true,
        specialties: ["Cardiology", "Oncology", "Transplant", "Pediatrics", "Neurosurgery", "Orthopedics"],
        avgRating: 4.7,
        reviewCount: 6,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Ibn Sina Hospital",
        slug: "ibn-sina-hospital-dhaka",
        type: HospitalType.PRIVATE,
        region: Region.BD,
        address: "House 48, Road 9/A, Dhanmondi, Dhaka-1209",
        city: "Dhaka",
        district: "Dhaka",
        lat: 23.748_2,
        lng: 90.377_6,
        phone: "+880-2-9660011",
        emergencyPhone: "+880-2-9660011",
        isOpen24h: false,
        openTime: "08:00",
        closeTime: "22:00",
        specialties: ["General Medicine", "Surgery", "Gynecology", "Orthopedics", "Radiology"],
        avgRating: 4.3,
        reviewCount: 5,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Chevron Clinical Laboratory",
        slug: "chevron-clinical-lab-chittagong",
        type: HospitalType.DIAGNOSTIC,
        region: Region.BD,
        address: "ENA Centre, 19 Agrabad C/A, Chittagong-4100",
        city: "Chittagong",
        district: "Chittagong",
        lat: 22.349_8,
        lng: 91.820_4,
        phone: "+880-31-726026",
        isOpen24h: false,
        openTime: "07:00",
        closeTime: "21:00",
        specialties: ["Pathology", "Radiology", "Cardiology", "Microbiology", "Molecular Diagnostics"],
        avgRating: 4.4,
        reviewCount: 4,
      },
    }),
  ])
  console.log("  ✓ Bangladesh hospitals")

  // ── US Doctors ───────────────────────────────────────────────────────────────
  const [us1, us2, us3, us4, us5, us6, us7, us8, us9, us10, us11, us12] =
    await Promise.all([
      // New York
      prisma.doctor.create({
        data: {
          name: "Dr. James Wilson",
          slug: "dr-james-wilson-ny",
          specialty: "Cardiology",
          bio: "Interventional cardiologist at NYU Langone. Specializes in complex coronary interventions, TAVR, and structural heart disease. Board-certified with 20+ years of practice.",
          region: Region.US,
          city: "New York",
          state: "NY",
          lat: 40.742_0,
          lng: -73.974_2,
          phone: "(212) 263-7300",
          email: "j.wilson@nyulangone.org",
          npi: "1234567890",
          consultFeeMin: 200,
          consultFeeMax: 400,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "tuesday", "thursday"], "08:00", "17:00", 20),
          isAvailableToday: true,
          avgWaitMinutes: 25,
          avgRating: 4.8,
          reviewCount: 8,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Sarah Chen",
          slug: "dr-sarah-chen-ny",
          specialty: "Neurology",
          bio: "Neurologist specializing in multiple sclerosis and neuro-immunology at NYU Langone. Research-active with publications in NEJM and Lancet Neurology.",
          region: Region.US,
          city: "New York",
          state: "NY",
          lat: 40.742_5,
          lng: -73.974_8,
          phone: "(212) 263-8100",
          email: "s.chen@nyulangone.org",
          npi: "2345678901",
          consultFeeMin: 250,
          consultFeeMax: 500,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "wednesday", "friday"], "09:00", "17:00", 16),
          isAvailableToday: false,
          avgWaitMinutes: 35,
          avgRating: 4.9,
          reviewCount: 7,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Michael Johnson",
          slug: "dr-michael-johnson-ny",
          specialty: "General Practice",
          bio: "Primary care physician serving the Lower East Side for 15 years. Bilingual (English/Spanish). Focus on preventive medicine and chronic disease management.",
          region: Region.US,
          city: "New York",
          state: "NY",
          lat: 40.716_0,
          lng: -73.985_0,
          phone: "(212) 555-0143",
          npi: "3456789012",
          consultFeeMin: 150,
          consultFeeMax: 300,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "tuesday", "wednesday", "thursday", "friday"], "08:00", "18:00", 28),
          isAvailableToday: true,
          avgWaitMinutes: 15,
          avgRating: 4.6,
          reviewCount: 6,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Emily Rodriguez",
          slug: "dr-emily-rodriguez-ny",
          specialty: "Gynecology",
          bio: "OB/GYN at Bellevue Hospital. Comprehensive women's healthcare including prenatal care, minimally invasive surgery, and menopause management.",
          region: Region.US,
          city: "New York",
          state: "NY",
          lat: 40.738_9,
          lng: -73.976_2,
          phone: "(212) 562-4141",
          email: "e.rodriguez@nychhc.org",
          npi: "4567890123",
          consultFeeMin: 200,
          consultFeeMax: 400,
          currency: "USD",
          chamberSchedule: usSchedule(["tuesday", "wednesday", "thursday", "friday"], "08:00", "16:00", 20),
          isAvailableToday: true,
          avgWaitMinutes: 30,
          avgRating: 4.7,
          reviewCount: 5,
        },
      }),
      // Chicago
      prisma.doctor.create({
        data: {
          name: "Dr. Robert Kim",
          slug: "dr-robert-kim-chicago",
          specialty: "Cardiology",
          bio: "Director of Cardiac Electrophysiology at Northwestern Medicine. Expert in atrial fibrillation, cardiac implantable devices, and catheter ablation.",
          region: Region.US,
          city: "Chicago",
          state: "IL",
          lat: 41.896_2,
          lng: -87.621_4,
          phone: "(312) 926-2000",
          email: "r.kim@nm.org",
          npi: "5678901234",
          consultFeeMin: 200,
          consultFeeMax: 350,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "wednesday", "friday"], "08:00", "17:00", 18),
          isAvailableToday: false,
          avgWaitMinutes: 40,
          avgRating: 4.8,
          reviewCount: 7,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Amanda Foster",
          slug: "dr-amanda-foster-chicago",
          specialty: "Diabetes & Endocrinology",
          bio: "Endocrinologist at Northwestern Medicine. Specializes in diabetes technology, insulin pump therapy, and thyroid cancer management.",
          region: Region.US,
          city: "Chicago",
          state: "IL",
          lat: 41.895_8,
          lng: -87.622_0,
          phone: "(312) 695-7970",
          email: "a.foster@nm.org",
          npi: "6789012345",
          consultFeeMin: 175,
          consultFeeMax: 300,
          currency: "USD",
          chamberSchedule: usSchedule(["tuesday", "thursday"], "08:30", "17:30", 16),
          isAvailableToday: true,
          avgWaitMinutes: 20,
          avgRating: 4.9,
          reviewCount: 6,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. David Patel",
          slug: "dr-david-patel-chicago",
          specialty: "General Practice",
          bio: "Family medicine physician in Lincoln Park, Chicago. Committed to accessible, patient-centered primary care for the whole family.",
          region: Region.US,
          city: "Chicago",
          state: "IL",
          lat: 41.922_3,
          lng: -87.635_0,
          phone: "(773) 555-0187",
          npi: "7890123456",
          consultFeeMin: 150,
          consultFeeMax: 250,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "tuesday", "wednesday", "thursday", "friday"], "07:30", "17:30", 30),
          isAvailableToday: true,
          avgWaitMinutes: 12,
          avgRating: 4.5,
          reviewCount: 5,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Lisa Thompson",
          slug: "dr-lisa-thompson-chicago",
          specialty: "Neurology",
          bio: "Neurologist at Northwestern Medicine specializing in headache medicine and concussion management. Developed the hospital's award-winning headache clinic.",
          region: Region.US,
          city: "Chicago",
          state: "IL",
          lat: 41.897_0,
          lng: -87.620_5,
          phone: "(312) 926-5685",
          email: "l.thompson@nm.org",
          npi: "8901234567",
          consultFeeMin: 225,
          consultFeeMax: 400,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "tuesday", "thursday"], "09:00", "16:00", 15),
          isAvailableToday: false,
          avgWaitMinutes: 45,
          avgRating: 4.7,
          reviewCount: 4,
        },
      }),
      // Los Angeles
      prisma.doctor.create({
        data: {
          name: "Dr. Carlos Martinez",
          slug: "dr-carlos-martinez-la",
          specialty: "Cardiology",
          bio: "Preventive cardiologist at Cedars-Sinai Smidt Heart Institute. Uses cutting-edge lipid management, advanced cardiac imaging, and lifestyle medicine.",
          region: Region.US,
          city: "Los Angeles",
          state: "CA",
          lat: 34.074_9,
          lng: -118.380_0,
          phone: "(310) 423-3277",
          email: "c.martinez@cshs.org",
          npi: "9012345678",
          consultFeeMin: 250,
          consultFeeMax: 500,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "wednesday", "friday"], "08:00", "16:00", 16),
          isAvailableToday: true,
          avgWaitMinutes: 30,
          avgRating: 4.8,
          reviewCount: 7,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Jennifer Lee",
          slug: "dr-jennifer-lee-la",
          specialty: "Gynecology",
          bio: "OB/GYN at Cedars-Sinai. High-volume surgeon in robotic and laparoscopic procedures. Named to LA Magazine Top Doctors list 5 years running.",
          region: Region.US,
          city: "Los Angeles",
          state: "CA",
          lat: 34.075_5,
          lng: -118.380_8,
          phone: "(310) 423-6100",
          email: "j.lee@cshs.org",
          npi: "1023456789",
          consultFeeMin: 200,
          consultFeeMax: 450,
          currency: "USD",
          chamberSchedule: usSchedule(["tuesday", "thursday"], "09:00", "16:30", 14),
          isAvailableToday: false,
          avgWaitMinutes: 50,
          avgRating: 4.9,
          reviewCount: 6,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. William Brown",
          slug: "dr-william-brown-la",
          specialty: "General Practice",
          bio: "Independent primary care physician in Silver Lake, Los Angeles. Known for unhurried appointments and thorough whole-patient assessments.",
          region: Region.US,
          city: "Los Angeles",
          state: "CA",
          lat: 34.089_9,
          lng: -118.272_6,
          phone: "(323) 555-0212",
          npi: "1134567890",
          consultFeeMin: 150,
          consultFeeMax: 280,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "tuesday", "wednesday", "thursday"], "08:00", "17:00", 24),
          isAvailableToday: true,
          avgWaitMinutes: 10,
          avgRating: 4.6,
          reviewCount: 5,
        },
      }),
      prisma.doctor.create({
        data: {
          name: "Dr. Maria Garcia",
          slug: "dr-maria-garcia-la",
          specialty: "Diabetes & Endocrinology",
          bio: "Endocrinologist serving the East Los Angeles community for 12 years. Fluent in Spanish. Focus on diabetes prevention and management in Latino populations.",
          region: Region.US,
          city: "Los Angeles",
          state: "CA",
          lat: 34.023_0,
          lng: -118.165_0,
          phone: "(323) 555-0265",
          npi: "1245678901",
          consultFeeMin: 175,
          consultFeeMax: 325,
          currency: "USD",
          chamberSchedule: usSchedule(["monday", "wednesday", "friday"], "08:00", "17:00", 22),
          isAvailableToday: true,
          avgWaitMinutes: 20,
          avgRating: 4.8,
          reviewCount: 5,
        },
      }),
    ])
  console.log("  ✓ US doctors")

  // ── US Hospitals ─────────────────────────────────────────────────────────────
  const [ush1, ush2, ush3, ush4, ush5] = await Promise.all([
    prisma.hospital.create({
      data: {
        name: "NYU Langone Health",
        slug: "nyu-langone-health",
        type: HospitalType.PRIVATE,
        region: Region.US,
        address: "550 First Avenue, New York, NY 10016",
        city: "New York",
        state: "NY",
        lat: 40.742_0,
        lng: -73.974_2,
        phone: "(212) 263-7300",
        emergencyPhone: "(212) 263-5550",
        isOpen24h: true,
        specialties: ["Cardiology", "Oncology", "Orthopedics", "Neurosurgery", "Transplant", "Rheumatology"],
        avgRating: 4.7,
        reviewCount: 9,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Northwestern Memorial Hospital",
        slug: "northwestern-memorial-hospital",
        type: HospitalType.PRIVATE,
        region: Region.US,
        address: "251 E Huron St, Chicago, IL 60611",
        city: "Chicago",
        state: "IL",
        lat: 41.896_2,
        lng: -87.621_4,
        phone: "(312) 926-2000",
        emergencyPhone: "(312) 926-5188",
        isOpen24h: true,
        specialties: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "Endocrinology"],
        avgRating: 4.6,
        reviewCount: 8,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Cedars-Sinai Medical Center",
        slug: "cedars-sinai-medical-center",
        type: HospitalType.PRIVATE,
        region: Region.US,
        address: "8700 Beverly Blvd, Los Angeles, CA 90048",
        city: "Los Angeles",
        state: "CA",
        lat: 34.074_9,
        lng: -118.380_0,
        phone: "(310) 423-3277",
        emergencyPhone: "(310) 423-4321",
        isOpen24h: true,
        specialties: ["Cardiology", "Oncology", "Neurosurgery", "Gynecology", "Orthopedics", "Urology"],
        avgRating: 4.8,
        reviewCount: 9,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Bellevue Hospital Center",
        slug: "bellevue-hospital-center",
        type: HospitalType.GOVERNMENT,
        region: Region.US,
        address: "462 First Avenue, New York, NY 10016",
        city: "New York",
        state: "NY",
        lat: 40.738_9,
        lng: -73.976_2,
        phone: "(212) 562-4141",
        emergencyPhone: "(212) 562-3015",
        isOpen24h: true,
        specialties: ["Emergency Medicine", "Psychiatry", "Surgery", "Internal Medicine", "Pediatrics"],
        avgRating: 4.0,
        reviewCount: 7,
      },
    }),
    prisma.hospital.create({
      data: {
        name: "Stroger Hospital of Cook County",
        slug: "stroger-hospital-cook-county",
        type: HospitalType.GOVERNMENT,
        region: Region.US,
        address: "1969 W Ogden Ave, Chicago, IL 60612",
        city: "Chicago",
        state: "IL",
        lat: 41.875_5,
        lng: -87.676_9,
        phone: "(312) 864-6000",
        emergencyPhone: "(312) 864-6000",
        isOpen24h: true,
        specialties: ["Trauma", "Surgery", "Internal Medicine", "Pediatrics", "Obstetrics"],
        avgRating: 3.9,
        reviewCount: 6,
      },
    }),
  ])
  console.log("  ✓ US hospitals")

  // ── Insurance Plans ──────────────────────────────────────────────────────────
  const [ins1, ins2, ins3] = await Promise.all([
    prisma.insurancePlan.create({
      data: {
        name: "BlueCross BlueShield Preferred PPO",
        provider: "BlueCross BlueShield",
        state: null,
        type: InsuranceType.PPO,
        deductible: 1500,
        copay: 30,
        outOfPocketMax: 5000,
        coverageDetails: {
          preventiveCare: "100% covered",
          primaryCare: "80% after deductible",
          specialist: "70% after deductible",
          emergency: "80% after deductible",
          mentalHealth: "80% after deductible",
          prescriptions: { generic: "$10 copay", brand: "$35 copay", specialty: "$75 copay" },
          outOfNetwork: "50% after deductible",
        },
      },
    }),
    prisma.insurancePlan.create({
      data: {
        name: "Aetna Choice POS II",
        provider: "Aetna",
        state: null,
        type: InsuranceType.HMO,
        deductible: 500,
        copay: 20,
        outOfPocketMax: 3500,
        coverageDetails: {
          preventiveCare: "100% covered",
          primaryCare: "$20 copay",
          specialist: "$40 copay (referral required)",
          emergency: "$150 copay then 80%",
          mentalHealth: "$20 copay",
          prescriptions: { generic: "$5 copay", brand: "$25 copay", specialty: "$60 copay" },
          outOfNetwork: "Not covered except emergency",
        },
      },
    }),
    prisma.insurancePlan.create({
      data: {
        name: "UnitedHealthcare Choice Plus HDHP",
        provider: "UnitedHealthcare",
        state: null,
        type: InsuranceType.HDHP,
        deductible: 3000,
        copay: 0,
        outOfPocketMax: 7000,
        coverageDetails: {
          preventiveCare: "100% covered (no deductible)",
          primaryCare: "100% after deductible",
          specialist: "100% after deductible",
          emergency: "100% after deductible",
          mentalHealth: "100% after deductible",
          prescriptions: { generic: "100% after deductible", brand: "100% after deductible", specialty: "100% after deductible" },
          hsaEligible: true,
          outOfNetwork: "60% after deductible",
        },
      },
    }),
  ])
  console.log("  ✓ Insurance plans")

  // ── Hospital–Insurance Links ──────────────────────────────────────────────────
  await prisma.hospitalInsurance.createMany({
    data: [
      { hospitalId: ush1.id, insurancePlanId: ins1.id },
      { hospitalId: ush1.id, insurancePlanId: ins2.id },
      { hospitalId: ush1.id, insurancePlanId: ins3.id },
      { hospitalId: ush2.id, insurancePlanId: ins1.id },
      { hospitalId: ush2.id, insurancePlanId: ins2.id },
      { hospitalId: ush3.id, insurancePlanId: ins1.id },
      { hospitalId: ush3.id, insurancePlanId: ins3.id },
      { hospitalId: ush4.id, insurancePlanId: ins1.id },
      { hospitalId: ush4.id, insurancePlanId: ins2.id },
      { hospitalId: ush4.id, insurancePlanId: ins3.id },
      { hospitalId: ush5.id, insurancePlanId: ins1.id },
      { hospitalId: ush5.id, insurancePlanId: ins2.id },
    ],
  })
  console.log("  ✓ Hospital–insurance links")

  // ── FQHC Affordable Clinics ──────────────────────────────────────────────────
  await prisma.affordableClinic.createMany({
    data: [
      {
        name: "Ryan Health | West 97th Street",
        address: "645 W 97th St",
        city: "New York",
        state: "NY",
        lat: 40.793_8,
        lng: -73.970_7,
        phone: "(212) 749-1820",
        isSliding: true,
        isFree: false,
        servicesOffered: ["Primary Care", "Dental", "Behavioral Health", "Pediatrics", "Women's Health", "HIV/AIDS Care"],
        languages: ["English", "Spanish", "Mandarin"],
        hours: {
          monday: "08:00-20:00",
          tuesday: "08:00-20:00",
          wednesday: "08:00-20:00",
          thursday: "08:00-20:00",
          friday: "08:00-18:00",
          saturday: "09:00-14:00",
        },
      },
      {
        name: "Charles B. Wang Community Health Center",
        address: "268 Canal St",
        city: "New York",
        state: "NY",
        lat: 40.717_5,
        lng: -73.999_7,
        phone: "(212) 379-6988",
        isSliding: true,
        isFree: false,
        servicesOffered: ["Primary Care", "Dental", "Optometry", "Mental Health", "Obstetrics", "Chronic Disease Management"],
        languages: ["English", "Mandarin", "Cantonese", "Fujianese"],
        hours: {
          monday: "08:30-18:00",
          tuesday: "08:30-18:00",
          wednesday: "08:30-18:00",
          thursday: "08:30-18:00",
          friday: "08:30-17:00",
        },
      },
      {
        name: "Erie Family Health Centers – Rogers Park",
        address: "1701 Howard St",
        city: "Chicago",
        state: "IL",
        lat: 42.019_2,
        lng: -87.672_6,
        phone: "(847) 492-2273",
        isSliding: true,
        isFree: false,
        servicesOffered: ["Primary Care", "Dental", "OB/GYN", "Pediatrics", "Behavioral Health", "Pharmacy"],
        languages: ["English", "Spanish", "Polish", "Russian"],
        hours: {
          monday: "08:00-20:00",
          tuesday: "08:00-20:00",
          wednesday: "08:00-20:00",
          thursday: "08:00-20:00",
          friday: "08:00-17:00",
          saturday: "08:00-12:00",
        },
      },
      {
        name: "Lawndale Christian Health Center",
        address: "3860 W Ogden Ave",
        city: "Chicago",
        state: "IL",
        lat: 41.855_1,
        lng: -87.720_5,
        phone: "(773) 854-2800",
        isSliding: true,
        isFree: false,
        servicesOffered: ["Primary Care", "Pediatrics", "OB/GYN", "Dental", "Mental Health", "Sports Medicine"],
        languages: ["English", "Spanish"],
        hours: {
          monday: "08:00-17:00",
          tuesday: "08:00-17:00",
          wednesday: "08:00-17:00",
          thursday: "08:00-17:00",
          friday: "08:00-17:00",
        },
      },
      {
        name: "St. John's Well Child and Family Center",
        address: "1721 S Broadway",
        city: "Los Angeles",
        state: "CA",
        lat: 34.038_6,
        lng: -118.265_2,
        phone: "(213) 744-1400",
        isSliding: true,
        isFree: true,
        servicesOffered: ["Primary Care", "Dental", "Mental Health", "WIC", "Pediatrics", "Immunizations", "Family Planning"],
        languages: ["English", "Spanish", "Tagalog", "Korean"],
        hours: {
          monday: "08:00-17:00",
          tuesday: "08:00-19:00",
          wednesday: "08:00-17:00",
          thursday: "08:00-19:00",
          friday: "08:00-17:00",
          saturday: "09:00-13:00",
        },
      },
      {
        name: "Northeast Valley Health Corporation – Pacoima",
        address: "11209 Glenoaks Blvd",
        city: "Los Angeles",
        state: "CA",
        lat: 34.264_5,
        lng: -118.408_6,
        phone: "(818) 896-7191",
        isSliding: true,
        isFree: false,
        servicesOffered: ["Primary Care", "Dental", "OB/GYN", "Mental Health", "Substance Abuse", "Vision", "Pharmacy"],
        languages: ["English", "Spanish", "Armenian"],
        hours: {
          monday: "07:30-17:00",
          tuesday: "07:30-17:00",
          wednesday: "07:30-17:00",
          thursday: "07:30-17:00",
          friday: "07:30-16:00",
        },
      },
    ],
  })
  console.log("  ✓ FQHC affordable clinics")

  // ── Cost Estimates ────────────────────────────────────────────────────────────
  await prisma.costEstimate.createMany({
    data: [
      // Bangladesh
      { procedureName: "MRI Brain", region: Region.BD, avgCostInsured: 3500, avgCostUninsured: 5000, currency: "BDT", source: "DMCH & Square Hospital avg 2024" },
      { procedureName: "Complete Blood Count (CBC)", region: Region.BD, avgCostInsured: 300, avgCostUninsured: 450, currency: "BDT", source: "Chevron & Popular Lab 2024" },
      { procedureName: "Chest X-Ray", region: Region.BD, avgCostInsured: 400, avgCostUninsured: 600, currency: "BDT", source: "National average 2024" },
      { procedureName: "ECG / EKG", region: Region.BD, avgCostInsured: 250, avgCostUninsured: 400, currency: "BDT", source: "National average 2024" },
      { procedureName: "Ultrasound Abdomen", region: Region.BD, avgCostInsured: 1200, avgCostUninsured: 2000, currency: "BDT", source: "Private hospital avg 2024" },
      { procedureName: "HbA1c Test", region: Region.BD, avgCostInsured: 500, avgCostUninsured: 800, currency: "BDT", source: "BIRDEM & Chevron 2024" },
      { procedureName: "Echocardiogram", region: Region.BD, avgCostInsured: 2500, avgCostUninsured: 4500, currency: "BDT", source: "NICVD & Square Hospital 2024" },
      { procedureName: "CT Scan Head", region: Region.BD, avgCostInsured: 5000, avgCostUninsured: 8000, currency: "BDT", source: "Private hospital avg 2024" },
      { procedureName: "Blood Glucose Test (FBS)", region: Region.BD, avgCostInsured: 150, avgCostUninsured: 250, currency: "BDT", source: "National average 2024" },
      { procedureName: "Urine Culture & Sensitivity", region: Region.BD, avgCostInsured: 600, avgCostUninsured: 900, currency: "BDT", source: "Chevron & Popular Lab 2024" },
      // United States
      { procedureName: "MRI Brain", region: Region.US, avgCostInsured: 650, avgCostUninsured: 2700, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "Complete Blood Count (CBC)", region: Region.US, avgCostInsured: 28, avgCostUninsured: 110, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "Chest X-Ray", region: Region.US, avgCostInsured: 120, avgCostUninsured: 370, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "ECG / EKG", region: Region.US, avgCostInsured: 65, avgCostUninsured: 200, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "Ultrasound Abdomen", region: Region.US, avgCostInsured: 250, avgCostUninsured: 700, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "HbA1c Test", region: Region.US, avgCostInsured: 35, avgCostUninsured: 140, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "Echocardiogram", region: Region.US, avgCostInsured: 820, avgCostUninsured: 2900, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "CT Scan Head", region: Region.US, avgCostInsured: 550, avgCostUninsured: 2500, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "Blood Glucose Test (FBS)", region: Region.US, avgCostInsured: 18, avgCostUninsured: 70, currency: "USD", source: "FAIR Health Consumer 2024" },
      { procedureName: "Urine Culture & Sensitivity", region: Region.US, avgCostInsured: 45, avgCostUninsured: 180, currency: "USD", source: "FAIR Health Consumer 2024" },
    ],
  })
  console.log("  ✓ Cost estimates")

  // ── Bangladesh Reviews (25) ───────────────────────────────────────────────────
  const bdUsers = [u1, u2, u3, u4, u5]
  const bdReviews: Prisma.ReviewCreateManyInput[] = [
    // Doctor reviews
    { userId: bdUsers[0].id, doctorId: bd1.id, punctualityRating: 3.5, qualityRating: 5, staffRating: 4, cleanlinessRating: 3, costFairnessRating: 4, overallRating: 4.5, body: "Professor Rahman is highly experienced doctor. He listened carefully to all symptoms and gave very good advice. Chamber was a bit crowded but staff managed nicely. Fee is reasonable for his level of expertise.", helpfulCount: 12 },
    { userId: bdUsers[1].id, doctorId: bd1.id, punctualityRating: 2, qualityRating: 4.5, staffRating: 3, cleanlinessRating: 3, costFairnessRating: 3.5, overallRating: 4, body: "Had to wait almost 2 hours even with appointment. But doctor bhai gave proper time during consultation. Diagnosed my father's heart problem correctly where other doctors failed. Will come again.", helpfulCount: 8 },
    { userId: bdUsers[2].id, doctorId: bd2.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 5, body: "Dr. Shahana is the best gynecologist in Dhaka, mashallah. She handled my high-risk pregnancy with extreme care. Square Hospital environment is also very good and clean. Highly recommend for all ladies.", helpfulCount: 22 },
    { userId: bdUsers[3].id, doctorId: bd2.id, punctualityRating: 4, qualityRating: 5, staffRating: 4, cleanlinessRating: 5, costFairnessRating: 2.5, overallRating: 4.5, body: "Doctor is excellent but consultation fee is quite high compared to others. If you can afford then she is best choice. Very knowledgeable and explained everything properly in simple language.", helpfulCount: 7 },
    { userId: bdUsers[4].id, doctorId: bd3.id, punctualityRating: 3, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 4, costFairnessRating: 3.5, overallRating: 4.5, body: "Dr. Farhad diagnosed my epilepsy correctly after many years of wrong diagnosis. He is very knowledgeable about brain diseases. Wait time is long but worth it. Alhamdulillah mother is much better now.", helpfulCount: 15 },
    { userId: bdUsers[0].id, doctorId: bd4.id, punctualityRating: 4, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 4.5, costFairnessRating: 4.5, overallRating: 5, body: "Dr. Nasrin apa is simply the best diabetes doctor in Bangladesh. She has deep knowledge and explains the disease very well. Fee is reasonable. BIRDEM hospital is also very well organized. Khub valo doctor.", helpfulCount: 19 },
    { userId: bdUsers[1].id, doctorId: bd4.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 4, cleanlinessRating: 4, costFairnessRating: 4, overallRating: 4.5, body: "Been seeing Dr. Nasrin for 5 years for my diabetes management. She keeps updated with latest medications and always adjusts treatment based on my reports. Highly recommended for diabetic patients.", helpfulCount: 11 },
    { userId: bdUsers[2].id, doctorId: bd5.id, punctualityRating: 4.5, qualityRating: 4, staffRating: 4.5, cleanlinessRating: 4, costFairnessRating: 5, overallRating: 4, body: "Dr. Islam is very affordable and easy to see without long waiting. Good for routine checkup and minor illness. Does not over-prescribe medicine which I appreciate. Good for middle class families.", helpfulCount: 6 },
    { userId: bdUsers[3].id, doctorId: bd6.id, punctualityRating: 4, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 2, overallRating: 4.5, body: "Evercare is the most expensive hospital but Dr. Tahmina is truly world class cardiologist. Very modern equipment, very clean facility, very professional staff. Worth the money if you can manage.", helpfulCount: 18 },
    { userId: bdUsers[4].id, doctorId: bd7.id, punctualityRating: 5, qualityRating: 4, staffRating: 4, cleanlinessRating: 3.5, costFairnessRating: 5, overallRating: 4, body: "Dr. Rafiqul is a very humble and caring doctor in Chittagong. Never rushes patients. Cost is very affordable. Little bit old fashioned but very knowledgeable. Local people all love him.", helpfulCount: 9 },
    { userId: bdUsers[0].id, doctorId: bd8.id, punctualityRating: 4, qualityRating: 4.5, staffRating: 4.5, cleanlinessRating: 4.5, costFairnessRating: 3.5, overallRating: 4.5, body: "Dr. Sadia at Chevron is very competent cardiologist for Chittagong. Modern diagnostic facilities available at Chevron which is big advantage. Bit pricey for Chittagong standard but quality is good.", helpfulCount: 7 },
    { userId: bdUsers[1].id, doctorId: bd10.id, punctualityRating: 3.5, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 4, costFairnessRating: 4, overallRating: 4.5, body: "Dr. Mahmuda handled my sister's delivery in Sylhet very professionally. She is very calm and reassuring during difficult moments. Highly recommended for expectant mothers in Sylhet region.", helpfulCount: 13 },
    { userId: bdUsers[2].id, doctorId: bd12.id, punctualityRating: 5, qualityRating: 4.5, staffRating: 4.5, cleanlinessRating: 4, costFairnessRating: 5, overallRating: 4.5, body: "Dr. Rezaul is Sylhet's most beloved doctor. He has been treating our family for over 15 years. Very affordable, very caring. Treats poor patients with same respect as rich patients. Allah bless him.", helpfulCount: 24 },
    // Hospital reviews
    { userId: bdUsers[3].id, hospitalId: bh1.id, punctualityRating: 2, qualityRating: 4, staffRating: 3, cleanlinessRating: 2.5, costFairnessRating: 5, overallRating: 3.5, body: "DMCH is government hospital so it is free or very cheap. Very crowded and long queue but doctors are genuinely good. If you are patient you can get good treatment. Best option for poor people of Bangladesh.", helpfulCount: 31 },
    { userId: bdUsers[4].id, hospitalId: bh1.id, punctualityRating: 1.5, qualityRating: 4, staffRating: 2.5, cleanlinessRating: 2, costFairnessRating: 5, overallRating: 3, body: "Very busy hospital. Sometimes have to wait whole day. Some staff are not very helpful but doctors are qualified and work very hard. Needs more staff and better management. But it serves millions of poor patients.", helpfulCount: 16 },
    { userId: bdUsers[0].id, hospitalId: bh2.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 4.5, body: "Square Hospital is one of the best private hospitals in Bangladesh. Everything is very organized and clean. Staff are well trained and polite. Expensive but you get what you pay for. Had my surgery here, excellent care.", helpfulCount: 28 },
    { userId: bdUsers[1].id, hospitalId: bh3.id, punctualityRating: 4, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 3.5, overallRating: 4.5, body: "BIRDEM is the best hospital for diabetes patients in South Asia I think. Very specialized. All equipment for diabetes care is available. Doctors are extremely experienced. My uncle's diabetic foot was saved here when others gave up hope.", helpfulCount: 33 },
    { userId: bdUsers[2].id, hospitalId: bh4.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 2, overallRating: 4.5, body: "Evercare is like a 5-star hospital in Bashundhara. Most modern equipment in Bangladesh. International standard of care. Very very expensive but quality is truly world class. Best option for serious illness.", helpfulCount: 21 },
    { userId: bdUsers[3].id, hospitalId: bh5.id, punctualityRating: 4, qualityRating: 4, staffRating: 4, cleanlinessRating: 4.5, costFairnessRating: 4, overallRating: 4, body: "Ibn Sina is good hospital in Dhanmondi area. Clean and organized. Doctors are good but sometimes wait is long. Price is moderate. Good for routine treatment and surgery. Friendly staff which matters a lot.", helpfulCount: 10 },
    { userId: bdUsers[4].id, hospitalId: bh6.id, punctualityRating: 4.5, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 5, costFairnessRating: 3.5, overallRating: 4.5, body: "Chevron is best diagnostic center in Chittagong. Very clean lab, modern machines, accurate results. Report comes quickly. Bit expensive but worth it for quality. I trust their test results completely.", helpfulCount: 14 },
    { userId: bdUsers[0].id, doctorId: bd9.id, punctualityRating: 4, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 4, costFairnessRating: 4, overallRating: 4.5, body: "Dr. Imran in Chittagong is very good diabetes doctor. Has good knowledge of latest insulin therapy. Explains treatment plan very clearly. Reasonable fee for specialist. Would recommend to all diabetic patients in Ctg.", helpfulCount: 8 },
    { userId: bdUsers[1].id, doctorId: bd11.id, punctualityRating: 3, qualityRating: 4.5, staffRating: 3.5, cleanlinessRating: 3.5, costFairnessRating: 4, overallRating: 4, body: "Dr. Ahsan is one of the few good neurologists in Sylhet. My father's Parkinson's disease is being managed well. Bit hard to get appointment but he is thorough in his examination. Very honest doctor.", helpfulCount: 11 },
    { userId: bdUsers[2].id, doctorId: bd6.id, punctualityRating: 3.5, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 1.5, overallRating: 4, body: "Dr. Tahmina is amazing cardiologist but cost is extremely high even by private hospital standard. 4000 taka just for consultation is too much for common people. Quality is there but not accessible for all.", helpfulCount: 9 },
    { userId: bdUsers[3].id, doctorId: bd3.id, punctualityRating: 2.5, qualityRating: 5, staffRating: 3.5, cleanlinessRating: 4, costFairnessRating: 3.5, overallRating: 4.5, body: "Best neurologist I have visited. Correctly identified cause of my husband's headaches after years of wrong treatment. Long wait is frustrating but his diagnosis is always accurate. Mashallah very talented doctor.", helpfulCount: 17 },
    { userId: bdUsers[4].id, doctorId: bd5.id, punctualityRating: 5, qualityRating: 4, staffRating: 4.5, cleanlinessRating: 4, costFairnessRating: 5, overallRating: 4, body: "Dr. Khondaker at Ibn Sina is very accessible doctor. Easy appointment, no long wait, affordable fee. Good for common illness and regular health checkup. Very kind with elderly patients.", helpfulCount: 6 },
  ]
  await prisma.review.createMany({ data: bdReviews })
  console.log("  ✓ Bangladesh reviews (25)")

  // ── US Reviews (25) ──────────────────────────────────────────────────────────
  const usUsers = [u6, u7, u8, u9, u10]
  const usReviews: Prisma.ReviewCreateManyInput[] = [
    // Doctor reviews
    { userId: usUsers[0].id, doctorId: us1.id, punctualityRating: 4, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 4.5, body: "Dr. Wilson is an exceptional cardiologist. He took the time to explain my condition in detail and outlined multiple treatment options. The staff at NYU Langone were incredibly professional. Expensive even with insurance.", helpfulCount: 14 },
    { userId: usUsers[1].id, doctorId: us1.id, punctualityRating: 3, qualityRating: 5, staffRating: 4, cleanlinessRating: 5, costFairnessRating: 2.5, overallRating: 4, body: "Great doctor but appointment was 6 weeks out and he ran 40 minutes late. Billing was confusing — got three separate bills. Medically excellent though, he caught something two other cardiologists missed.", helpfulCount: 11 },
    { userId: usUsers[2].id, doctorId: us2.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 5, body: "Dr. Chen is truly world-class. Managing my MS for 3 years now and I've seen dramatic improvement. She stays current with the latest research and always explains the science. Grateful to have her as my neurologist.", helpfulCount: 22 },
    { userId: usUsers[3].id, doctorId: us3.id, punctualityRating: 5, qualityRating: 4.5, staffRating: 4.5, cleanlinessRating: 4, costFairnessRating: 4.5, overallRating: 4.5, body: "Dr. Johnson is a fantastic primary care doctor — old school in the best way. Actually listens, does a thorough physical, and doesn't just rush to order tests. Accepts most insurance plans. Highly recommend.", helpfulCount: 18 },
    { userId: usUsers[4].id, doctorId: us3.id, punctualityRating: 4.5, qualityRating: 4, staffRating: 4, cleanlinessRating: 4, costFairnessRating: 4, overallRating: 4, body: "Solid primary care physician in the LES. Bilingual which is great for my family. Wait time is usually under 15 minutes. Office is a bit small but the quality of care is excellent.", helpfulCount: 7 },
    { userId: usUsers[0].id, doctorId: us4.id, punctualityRating: 4, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 4.5, costFairnessRating: 4, overallRating: 4.5, body: "Dr. Rodriguez delivered my baby at Bellevue and she was absolutely amazing throughout a complicated labor. Cool under pressure, communicated everything clearly. Couldn't be more grateful.", helpfulCount: 25 },
    { userId: usUsers[1].id, doctorId: us5.id, punctualityRating: 3, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 2.5, overallRating: 4.5, body: "Dr. Kim is one of the best EP cardiologists in the Midwest. My AFib is under control for the first time in years after his ablation procedure. Northwestern's cardiac program is phenomenal. Just expect to pay a lot.", helpfulCount: 16 },
    { userId: usUsers[2].id, doctorId: us6.id, punctualityRating: 5, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3.5, overallRating: 5, body: "Dr. Foster changed my life. After 10 years of poor diabetes control, she switched my therapy to a CGM/pump combo and my A1C dropped from 9.8 to 6.4. She's brilliant and genuinely cares about outcomes.", helpfulCount: 29 },
    { userId: usUsers[3].id, doctorId: us7.id, punctualityRating: 5, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 4, costFairnessRating: 5, overallRating: 4.5, body: "Dr. Patel is the rare primary care doc who actually spends time with you. 30-minute appointments feel real. His office accepts many insurance plans including Medicaid. Easy online scheduling. Highly recommended.", helpfulCount: 13 },
    { userId: usUsers[4].id, doctorId: us8.id, punctualityRating: 3.5, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 4.5, body: "Dr. Thompson runs the best headache clinic I've been to after visiting 5 neurologists. She correctly identified my chronic migraine subtype and created a tailored preventive regimen. Long wait for new patients (3 months) but worth it.", helpfulCount: 20 },
    { userId: usUsers[0].id, doctorId: us9.id, punctualityRating: 4, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 5, body: "Dr. Martinez at Cedars-Sinai is exceptional. Caught early signs of familial hypercholesterolemia my previous doctor missed. Very research-oriented approach. Facility is top-notch. Out-of-pocket cost was high but the care quality justified it.", helpfulCount: 17 },
    { userId: usUsers[1].id, doctorId: us10.id, punctualityRating: 3.5, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 2, overallRating: 4.5, body: "Dr. Lee is incredibly skilled — her robotic hysterectomy left me with minimal recovery time. But getting an appointment took months and the billing was a nightmare. Results were spectacular though. Worth the stress.", helpfulCount: 15 },
    { userId: usUsers[2].id, doctorId: us11.id, punctualityRating: 5, qualityRating: 4.5, staffRating: 4.5, cleanlinessRating: 4, costFairnessRating: 4.5, overallRating: 4.5, body: "Dr. Brown in Silver Lake is an outstanding primary care physician. Small independent practice means he actually knows his patients. Never feel like a number. Takes time to discuss lifestyle factors not just medications.", helpfulCount: 12 },
    { userId: usUsers[3].id, doctorId: us12.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 5, cleanlinessRating: 4.5, costFairnessRating: 4.5, overallRating: 5, body: "Dr. Garcia is amazing — she is fluent in Spanish and really understands the cultural context of managing diabetes in our community. She's patient, thorough, and accepts most plans including Medi-Cal. A treasure for East LA.", helpfulCount: 26 },
    // Hospital reviews
    { userId: usUsers[4].id, hospitalId: ush1.id, punctualityRating: 3.5, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 2, overallRating: 4.5, body: "NYU Langone is a world-class facility. State-of-the-art equipment, excellent nursing staff, and top physicians. The main downside is cost — even with good insurance my out-of-pocket was substantial. But medically, truly excellent.", helpfulCount: 23 },
    { userId: usUsers[0].id, hospitalId: ush1.id, punctualityRating: 4, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 2.5, overallRating: 4.5, body: "Had a complex surgery at NYU Langone. Pre-op team, surgeons, anesthesiologists, and recovery nurses were all exceptional. The level of coordination and communication was impressive. Hospital billing is opaque — need to improve that.", helpfulCount: 18 },
    { userId: usUsers[1].id, hospitalId: ush2.id, punctualityRating: 4.5, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3, overallRating: 5, body: "Northwestern Memorial is consistently ranked among the best hospitals in America and the experience confirms it. Friendly staff, minimal wait, spotless rooms. Cardiologist was exceptional. Wish it was more affordable but the care is worth it.", helpfulCount: 20 },
    { userId: usUsers[2].id, hospitalId: ush3.id, punctualityRating: 4, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 2, overallRating: 4.5, body: "Cedars-Sinai is simply the best hospital in LA and possibly the country. Beautiful facility, zero infections, incredible doctors. The concierge-style care is unmatched. Very expensive but if you have good insurance it's worth every penny.", helpfulCount: 27 },
    { userId: usUsers[3].id, hospitalId: ush4.id, punctualityRating: 2.5, qualityRating: 4, staffRating: 3.5, cleanlinessRating: 3.5, costFairnessRating: 5, overallRating: 3.5, body: "Bellevue is a public hospital so it's understaffed and crowded but the doctors are genuinely good. They treat everyone regardless of ability to pay which is admirable. ER wait times can be 6+ hours. Best option for uninsured New Yorkers.", helpfulCount: 34 },
    { userId: usUsers[4].id, hospitalId: ush4.id, punctualityRating: 3, qualityRating: 4.5, staffRating: 4, cleanlinessRating: 3.5, costFairnessRating: 5, overallRating: 4, body: "I was uninsured when I came to Bellevue for an appendectomy. They treated me without discrimination and the surgery team was excellent. Billing was on a sliding scale. This is what public healthcare should look like.", helpfulCount: 21 },
    { userId: usUsers[0].id, hospitalId: ush5.id, punctualityRating: 2.5, qualityRating: 4, staffRating: 3.5, cleanlinessRating: 3.5, costFairnessRating: 5, overallRating: 3.5, body: "Stroger does remarkable work as a safety-net hospital. Trauma team is excellent. Very long waits in non-emergency situations but for truly critical cases they are fast and competent. Critical resource for Chicago's underserved communities.", helpfulCount: 15 },
    { userId: usUsers[1].id, doctorId: us2.id, punctualityRating: 4, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 3.5, overallRating: 5, body: "Dr. Chen monitors my MS very closely with regular MRIs and adjusts treatment proactively. I've had zero relapses in 2 years. Her team responds quickly to messages through MyChart. Truly a life-changing physician.", helpfulCount: 19 },
    { userId: usUsers[2].id, hospitalId: ush2.id, punctualityRating: 4, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 3.5, overallRating: 4.5, body: "Admitted for a cardiac event at Northwestern — the response time was outstanding. ICU nurses were attentive around the clock. Discharge planning was thorough with clear follow-up instructions. Genuinely impressed.", helpfulCount: 16 },
    { userId: usUsers[3].id, doctorId: us6.id, punctualityRating: 5, qualityRating: 5, staffRating: 5, cleanlinessRating: 5, costFairnessRating: 4, overallRating: 5, body: "Dr. Foster is the most thorough endocrinologist I've ever seen. She spends 45 minutes per visit, reviews all data, and explains everything. Her nurse educator is also fantastic. My whole family now sees her.", helpfulCount: 24 },
    { userId: usUsers[4].id, doctorId: us9.id, punctualityRating: 3.5, qualityRating: 5, staffRating: 4.5, cleanlinessRating: 5, costFairnessRating: 2.5, overallRating: 4.5, body: "Dr. Martinez caught a calcium score of 340 that puts me at high cardiovascular risk. Nobody else had tested for this. He created a comprehensive prevention plan. Cost was very high but the early detection may have saved my life.", helpfulCount: 22 },
  ]
  await prisma.review.createMany({ data: usReviews })
  console.log("  ✓ US reviews (25)")

  console.log("\n✅  Seed complete!")
  console.log(`   Users: 10 | BD Doctors: 12 | US Doctors: 12`)
  console.log(`   BD Hospitals: 6 | US Hospitals: 5`)
  console.log(`   Insurance Plans: 3 | FQHC Clinics: 6`)
  console.log(`   Cost Estimates: 20 | Reviews: 50 (25 BD + 25 US)`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
